on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        id: version
        # Get version from project.clj
        run: echo ::set-output name=zprint::$(awk -F "\"" '{print $2}' project.clj | head -n 1)

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
          lein: 2.9.1                  # Leiningen

      - name: Uberjar
        run: lein uberjar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: target/zprint-filter-${{ steps.version.outputs.zprint }}
